### ISSUE TITLE
Iso-Seq2 vs Iso-Seq3

### ISSUE THREAD

**Issue by ke-shi** [PacificBiosciences/IsoSeq3#12]
We want to use the Iso-Seq data for gene prediction in de novo genome sequencing. We tried Iso-Seq2 and Iso-Seq3 for transcriptome data from four Sequel SMRT cells to compare the results. 

(1) The resultant HQ sequence numbers and sizes were similar: 68,999 seqs (total length of 116.8 Mb) from Iso-Seq3 and 73,930 seqs (133.5 Mb) from Iso-Seq2. However, LQ were quite different: 273,588 seqs (537.8 Mb) from Iso-Seq2 and 1,800 seqs (2.6 Mb) from Iso-Seq3. The LQ from Iso-Seq2 were indeed mapped on gene regions of the reference genome. Why did not Iso-Seq3 produce LQ sequences?

(2) The Iso-Seq2 HQ covered 14 Mb genome regions and Iso-Seq3 HQ also covered 14 Mb. However, only 10 Mb was overlapped, the remaining 4 and 4 Mb were specific to Iso-Seq2 and Iso-Seq3. Why is the overlapping so small?

For the gene prediction purpose, Iso-Seq2 and Iso-Seq3 should be combined to get much more information rather than only Iso-Seq3. Is this correct?

**Comment by Magdoll** [comment]
Hi @ke-shi ,

(1) The major reduction in number of Iso-Seq3 LQ is because Iso-Seq3 does not output any singleton clusters (i.e. a cluster containing a single FL read). Iso-Seq2 on the other hand will include singleton clusters in LQ. This was mentioned in an earlier issue. We may consider putting the singleton clusters back in LQ in the future. 

(2) Our in-house human Iso-Seq dataset showed Iso-Seq2 and Iso-Seq3 to be > 95% concordant on capturing known human genes, so the high discrepancy you describe here is unexpected. See slide 33-34 in [this Iso-Seq3 slide deck](https://www.dropbox.com/s/0hlqi7b79kzi8bh/20180517_AsiaUGM_BioinformaticsDeck_English_V5.pdf?dl=0). However, could you please elaborate on the 4MB that is unique to Iso-Seq2 only? Are these mostly single exon (unspliced) transcripts? We see a major reduction in "Genic Intron" (that is, single exon sequences) Iso-Seq3 which we believe are mostly artifacts. 


--Liz

**Comment by ke-shi** [comment]
Thanks Liz, I will wait for the new version of Iso-Seq3.
